
export const FRIENDS_LIST_ASNYC = 'FRIENDS_LIST_ASNYC';
export const FRIENDS_LOADING = 'FRIENDS_LOADING';
export const FRIENDS_SUCCESS = 'FRIENDS_SUCCESS';
export const FRIENDS_ERROR = 'FRIENDS_ERROR';
